"""Initial Migration

Revision ID: 939912e1be2c
Revises: bf89f1f67495
Create Date: 2020-05-10 20:26:44.420151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '939912e1be2c'
down_revision = 'bf89f1f67495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.String(length=225), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###
